name: Build & Deploy for Development

on: workflow_dispatch

jobs:
  build:
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: Build the project
        run: go build -v ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
      - name: Check if the dev directory exists
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '[ ! -d ~/dev ] && mkdir ~/dev || echo "Directory already exists"'
      - name: Synchronize files with rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/dev
      - name: Start the application
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'cd ~/dev && go run main.go'
